# Problem 1
Bir YetGenli yeni aldığı bahçesinin etrafına çit çevirmek istiyor. Bahçenin etrafını çit ile çevirmek için gerekli çit uzunluğunu ve bahçenin alanını hesaplayan fonksiyonu yazınız.

In [5]:
def bahçe(a,b):
    alan = a * b
    citmiktari = 2*(a+b)
    print(alan)
    print(citmiktari)
bahçe(2,6)
#a ve b bahçenin kenar uzunlukları

12
16

# Problem 2
Kendisine gönderilen 2 sayı arasındaki tüm asal sayıları bulan fonksiyonu yazınız.

In [19]:
def asalsayi(a,b):
    for i in range(a,b+1):
        if i % range(2,int(i/2+1)) != 0:
            print(i)
asalsayi(99,456)

TypeError: unsupported operand type(s) for %: 'int' and 'range'

# Problem 3
YetGen liderlerinin kurdukları girişim unicorn oluyor. YetGen liderleri iş arkadaşlarının alacağı ücretlerini hesaplamak için bir fonksiyon yazdılar. Bu fonksiyonu kullanarak, YetGen liderlerinin iş arkadaşlarına verecekleri ücretleri hesaplayınız.

Ücret hesaplanması çalışma saatine bağlıdır. Bunun için kullanıcıdan çalışma saati bilgisinn alın. Sonrasında yapılacak ödemenin hesaplanacağı computePay() adlı bir fonksiyon oluşturun. Bu fonksiyonun içinde işlemler yapın. Çalışma saati 40 ve altındaysa saat başına ücret 10 TL’dir. 40 saatin üstünde çalışıldıysa saat başına ücret 15 TL sayılmaktadır.

```
Test etmek için 30 saat değerini giriniz,  sonuç 300 TL çıkmalı, 
ikincil test olarak 50 değerini giriniz,  sonuç 750 TL çıkmalı.
```

In [23]:
def maashesap(a):
    if a <= 40:
        print(a*10)
    elif a > 40:
        print(a*15)
maashesap(56)

840

# Problem 4
YetGenliler zirveye gitmek için toplanıyor. Zirveye gitmek için kiraladıkları araçlar 4'er kişiliktir. Gelecek kişi sayısı için Airtable üzerinde form açılıyor. Gelecek kişi sayısını alıp dört kişilik araçlara bölüp kalan kişi sayısını döndüren bir fonksiyon yazınız.

In [4]:
def kisiSayısıhesapla(kisisayısı):
    return kisisayısı % 4
kisi = int(input("kackişi geliyor"))
print(kisiSayısıhesapla(kisi))

2

# Problem 5
sayiTopla() adında bir fonksiyon yazın. sayiTopla() fonksiyonu girilen sayıları toplayarak yazdırmasını sağlayan bir fonksiyon yazınız.

Örneğin sayiTopla(1,2,3,4,5) yazdığımızda 15 çıktısını almalıyız. sayiTopla(1,2,3,4,5,6,7,8,9,10) yazdığımızda 55 çıktısını almalıyız.

In [25]:
def sayitopla(*x):
    toplam = *x
    print(toplam)
sayitopla(2,34,65,78,9,1,23,41)

SyntaxError: can't use starred expression here (3438085185.py, line 2)

# Problem 6

[("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)] listesi içerisinde verilen elemanların her birini tuple içindeki 2. Elemana göre sıralayınız.

In [5]:
data = [("xxx",1),("xxx",2),("xxx",9),("xxx",3), ("xxx",1),("xxx",13),("xxx",26),("xxx",4)]
data.sort(key=lambda tup:tup[1])
print(data)

[('xxx', 1), ('xxx', 1), ('xxx', 2), ('xxx', 3), ('xxx', 4), ('xxx', 9), ('xxx', 13), ('xxx', 26)]

# Problem 7
List comprehension kullanarak 1'den 100'e kadar olan sayılardan sadece çift sayıları bir listeye atmayı yapmayı çalışın.

In [1]:

cift_sayilar = [sayi for sayi in range(1, 101) if sayi % 2 == 0]
print(cift_sayilar)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]